"""Generate sample data for testing."""

import pandas as pd
from datetime import datetime, timedelta
from pathlib import Path

def generate_sample_data():
    """Generate 25 diverse change request samples."""
    
    samples = [
        # Low-risk configurations (should approve)
        {
            "Short Description": "Update nginx worker process count to 8",
            "Long Description": "Setting worker_processes to 8 to better utilize 8-core CPU resources based on load testing results",
            "Change Type": "standard",
            "Change Category": "configuration",
            "Implementation Steps": "1. SSH to prod-web-01\n2. Edit /etc/nginx/nginx.conf: worker_processes 8\n3. Test config: nginx -t\n4. Reload: systemctl reload nginx\n5. Monitor /var/log/nginx/error.log",
            "Validation Steps": "1. Check processes: ps aux | grep nginx\n2. Load test with 1000 req/sec\n3. Monitor CPU utilization\n4. Check response times",
            "Rollback Plan": "1. Revert nginx.conf to worker_processes 4\n2. Test: nginx -t\n3. Reload nginx\n4. Verify with load test",
            "Planned Window": "2024-02-20T23:00:00Z",
            "Impacted Services": "Web Server",
            "Complexity": "low",
        },
        {
            "Short Description": "Add read-only database user for analytics team",
            "Long Description": "Creating new database user with SELECT-only privileges for analytics team to run queries on production database without risk of modifications",
            "Change Type": "standard",
            "Change Category": "configuration",
            "Implementation Steps": "1. Connect to MySQL master\n2. Run: CREATE USER 'analytics_ro'@'%' IDENTIFIED BY '[secure_password]'\n3. GRANT SELECT ON database.* TO 'analytics_ro'@'%'\n4. FLUSH PRIVILEGES\n5. Test with analytics team credentials",
            "Validation Steps": "1. Verify user created: SELECT user FROM mysql.user\n2. Test SELECT query works\n3. Verify INSERT/UPDATE fails\n4. Document in access control sheet",
            "Rollback Plan": "1. DROP USER 'analytics_ro'@'%'\n2. FLUSH PRIVILEGES\n3. Verify access removed",
            "Planned Window": "2024-02-21T10:00:00Z",
            "Impacted Services": "Database",
            "Complexity": "low",
        },
        {
            "Short Description": "Update DNS A record for new IP address",
            "Long Description": "DNS record for api.company.com needs to point to new load balancer IP 203.0.113.45 after infrastructure migration",
            "Change Type": "standard",
            "Change Category": "configuration",
            "Implementation Steps": "1. Access DNS management console\n2. Update A record api.company.com\n3. Old IP: 192.0.2.50\n4. New IP: 203.0.113.45\n5. Set TTL to 300 seconds\n6. Apply changes",
            "Validation Steps": "1. Query DNS: nslookup api.company.com\n2. Verify resolution to new IP\n3. Monitor for 10 minutes\n4. Check load balancer health",
            "Rollback Plan": "1. Revert A record to 192.0.2.50\n2. Set TTL to 300\n3. Monitor connectivity",
            "Planned Window": "2024-02-22T22:00:00Z",
            "Impacted Services": "API Gateway, Load Balancer",
            "Complexity": "low",
        },
        {
            "Short Description": "Enable gzip compression in web server",
            "Long Description": "Enable gzip compression for HTTP responses to reduce bandwidth usage. Compression tested with various file types.",
            "Change Type": "standard",
            "Change Category": "configuration",
            "Implementation Steps": "1. SSH to web servers\n2. Edit /etc/apache2/mods-available/deflate.conf\n3. Enable: a2enmod deflate\n4. Restart Apache: systemctl restart apache2\n5. Verify in headers",
            "Validation Steps": "1. Check header: curl -I http://localhost | grep -i encoding\n2. Test page size reduction: curl | wc -c\n3. Load test performance\n4. Browser verification",
            "Rollback Plan": "1. a2dismod deflate\n2. systemctl restart apache2\n3. Verify non-compressed responses",
            "Planned Window": "2024-02-23T03:00:00Z",
            "Impacted Services": "Web Server, CDN",
            "Complexity": "low",
        },
        
        # Medium-risk deployments (need review)
        {
            "Short Description": "Deploy API v2.1.0 with user profile endpoint",
            "Long Description": "Deploying new API v2.1.0 containing new user profile endpoint with improved caching strategy. Tested in staging for 1 week.",
            "Change Type": "normal",
            "Change Category": "deployment",
            "Implementation Steps": "1. Pull release v2.1.0 from registry\n2. Blue-green deployment: deploy to green env\n3. Run smoke tests\n4. Switch traffic: haproxy reload\n5. Monitor green environment\n6. Blue kept as rollback",
            "Validation Steps": "1. Health checks on new endpoints\n2. Load test: 2000 req/sec for 10 min\n3. Check error rates vs baseline\n4. Verify latency within SLA\n5. Monitor CPU/memory usage",
            "Rollback Plan": "1. Detect issue in canary (5% traffic)\n2. Switch traffic back to v2.0.5\n3. Investigate in green environment\n4. Roll forward with fix after 24 hours",
            "Planned Window": "2024-02-20T22:00:00Z",
            "Impacted Services": "API Gateway, API Service, User Database, Cache",
            "Complexity": "medium",
        },
        {
            "Short Description": "Database query optimization for user listings",
            "Long Description": "Adding index on users.email column to improve query performance for user lookups. Query currently takes 2 seconds for 1M users, should reduce to <100ms.",
            "Change Type": "normal",
            "Change Category": "database",
            "Implementation Steps": "1. Backup users table\n2. ANALYZE TABLE users\n3. CREATE INDEX idx_email ON users(email)\n4. Monitor slow query log\n5. Update query execution plan",
            "Validation Steps": "1. Query explain plan shows index usage\n2. Run SHOW INDEX from users\n3. Benchmark query: SELECT ... WHERE email='test@example.com'\n4. Performance should be <100ms",
            "Rollback Plan": "1. DROP INDEX idx_email ON users\n2. Run ANALYZE TABLE users again\n3. Verify performance reverted",
            "Planned Window": "2024-02-21T02:00:00Z",
            "Impacted Services": "Database, User Service",
            "Complexity": "medium",
        },
        {
            "Short Description": "Scale Redis cache cluster to 5 nodes",
            "Long Description": "Increase Redis cluster from 3 to 5 nodes to handle 50% higher traffic load forecasted for Q2. Current node at 80% capacity.",
            "Change Type": "normal",
            "Change Category": "infrastructure",
            "Implementation Steps": "1. Provision 2 new Redis instances\n2. Config: redis.conf with cluster mode\n3. Add nodes to cluster: CLUSTER MEET\n4. Rebalance slots: CLUSTER SLOTS\n5. Monitor memory usage\n6. Enable persistence monitoring",
            "Validation Steps": "1. Verify 5 nodes in cluster: CLUSTER NODES\n2. Test with cache load\n3. Monitor memory per node (<70%)\n4. Test failover scenarios\n5. Performance benchmark",
            "Rollback Plan": "1. Remove new nodes from cluster\n2. Rebalance to 3 nodes\n3. Decommission new instances\n4. Verify application connectivity",
            "Planned Window": "2024-02-22T01:00:00Z",
            "Impacted Services": "Cache, Search Service, Session Store",
            "Complexity": "medium",
        },
        {
            "Short Description": "Update SSL certificate for *.api.company.com",
            "Long Description": "Renewing wildcard SSL certificate expiring in 7 days. New cert valid for 1 year. Zero-downtime update with HAProxy.",
            "Change Type": "normal",
            "Change Category": "infrastructure",
            "Implementation Steps": "1. Generate new CSR for *.api.company.com\n2. Obtain new certificate from CA\n3. Copy new cert to /etc/ssl/certs/\n4. Update HAProxy config\n5. HAProxy reload (graceful)\n6. Verify cert in browser",
            "Validation Steps": "1. Check cert: openssl s_client -connect api.company.com:443\n2. Verify expiry date\n3. Check certificate chain\n4. Browser validation (no warnings)\n5. API endpoint verification",
            "Rollback Plan": "1. Restore old cert file\n2. HAProxy reload\n3. Verify old cert active",
            "Planned Window": "2024-02-20T20:00:00Z",
            "Impacted Services": "API Gateway, Load Balancer, All API Services",
            "Complexity": "medium",
        },
        
        # Higher risk changes (likely review or reject)
        {
            "Short Description": "Migrate user data to MongoDB - Phase 1",
            "Long Description": "Phase 1 of user data migration from PostgreSQL to MongoDB. Includes user profiles, preferences. Data consistency checks required. No rollback tested.",
            "Change Type": "normal",
            "Change Category": "database",
            "Implementation Steps": "1. Export user data from PostgreSQL\n2. Transform to MongoDB format\n3. Import to MongoDB cluster\n4. Run sanity checks\n5. Update application ORM",
            "Validation Steps": "1. Row count comparison\n2. Data type verification\n3. Query performance comparison\n4. User session tests",
            "Rollback Plan": "Would require full data resync - not tested",
            "Planned Window": "2024-02-25T00:00:00Z",
            "Impacted Services": "Database, User Service, Authentication, Session Manager",
            "Complexity": "high",
        },
        {
            "Short Description": "Emergency hotfix: CRITICAL XSS vulnerability in profile editor",
            "Long Description": "CRITICAL security issue discovered: User input not sanitized in profile bio field. Attacker can inject JavaScript affecting all users viewing the profile.",
            "Change Type": "emergency",
            "Change Category": "deployment",
            "Implementation Steps": "1. Deploy hotfix v2.0.1 immediately\n2. Apply input sanitization on bio field\n3. Validate all profile endpoints\n4. Clear cached profiles",
            "Validation Steps": "1. Attempt XSS payload injection - should be escaped\n2. Verify profile display works\n3. Check database for malicious content\n4. Monitor error rates",
            "Rollback Plan": "1. If critical issues, rollback to v2.0.0\n2. Keep hotfix branch for investigation",
            "Planned Window": "2024-02-19T14:30:00Z",
            "Impacted Services": "API Service, Web Frontend, User Database",
            "Complexity": "high",
        },
        {
            "Short Description": "Backup system disk space cleanup - rm old logs",
            "Long Description": "Backup partition at 95% capacity. Need to delete old application logs to free up space.",
            "Change Type": "standard",
            "Change Category": "configuration",
            "Implementation Steps": "1. SSH to backup server\n2. Run: rm -rf /backup/logs/2023/*\n3. Run: df -h to verify space",
            "Validation Steps": "Confirm disk space increased",
            "Rollback Plan": "None - data is gone",
            "Planned Window": "2024-02-20T15:00:00Z",
            "Impacted Services": "Backup System",
            "Complexity": "low",
        },
        {
            "Short Description": "Production database master failover test",
            "Long Description": "Testing MySQL master-slave failover to ensure HA works. Switch production writes to replica and back.",
            "Change Type": "normal",
            "Change Category": "infrastructure",
            "Implementation Steps": "1. Put old master in read-only mode\n2. Promote replica to master\n3. Update app connection strings\n4. Run smoke tests\n5. Demote old master to replica\n6. Verify replication",
            "Validation Steps": "1. Verify writes go to new master\n2. Check replication lag: SHOW SLAVE STATUS\n3. Query all critical tables\n4. Monitor for errors",
            "Rollback Plan": "Promote original master back if issues occur (tested previously)",
            "Planned Window": "2024-02-21T04:00:00Z",
            "Impacted Services": "Database, All Services Using DB",
            "Complexity": "high",
        },
        
        # Problematic changes (should require review or reject)
        {
            "Short Description": "Update production configuration file",
            "Long Description": "Some configuration updates needed in production",
            "Change Type": "standard",
            "Change Category": "configuration",
            "Implementation Steps": "Update config files",
            "Validation Steps": "Test",
            "Rollback Plan": "Revert if needed",
            "Planned Window": "2024-02-20T08:00:00Z",
            "Impacted Services": "Multiple",
            "Complexity": "medium",
        },
        {
            "Short Description": "Payment processing system maintenance",
            "Long Description": "Performing maintenance on critical payment system. Very critical but under-documented.",
            "Change Type": "normal",
            "Change Category": "infrastructure",
            "Implementation Steps": "1. Perform maintenance\n2. Restart service\n3. Monitor",
            "Validation Steps": "Check if it works",
            "Rollback Plan": "Restart if broken",
            "Planned Window": "2024-02-21T10:00:00Z",
            "Impacted Services": "Payment Gateway, Payment Service, Billing Database, Accounting System",
            "Complexity": "high",
        },
        {
            "Short Description": "Cache layer upgrade from Redis 5 to 6",
            "Long Description": "Redis version upgrade from 5.0 to 6.2 LTS. Major version change with new features.",
            "Change Type": "normal",
            "Change Category": "infrastructure",
            "Implementation Steps": "1. Download Redis 6.2\n2. Compile from source\n3. Stop Redis 5\n4. Change /etc/redis.conf to point to new binary\n5. Start Redis 6.2\n6. Check if keys migrated",
            "Validation Steps": "1. Check Redis version: redis-cli --version\n2. Run some cache gets\n3. Monitor",
            "Rollback Plan": "Switch back to /opt/redis-5/bin/redis-server",
            "Planned Window": "2024-02-22T22:00:00Z",
            "Impacted Services": "Cache, Session Store, Search Service",
            "Complexity": "high",
        },
        
        # More samples with variety
        {
            "Short Description": "Add monitoring dashboard for API latency",
            "Long Description": "Creating new Grafana dashboard to monitor P50, P95, P99 latencies for all API endpoints. Uses existing Prometheus metrics.",
            "Change Type": "standard",
            "Change Category": "configuration",
            "Implementation Steps": "1. Access Grafana UI\n2. Create new dashboard\n3. Add panels for API latency queries\n4. Save dashboard\n5. Share with team",
            "Validation Steps": "1. Dashboard displays correctly\n2. Metrics update in real-time\n3. Alert rules functional",
            "Rollback Plan": "Delete dashboard from Grafana",
            "Planned Window": "2024-02-20T12:00:00Z",
            "Impacted Services": "Monitoring System",
            "Complexity": "low",
        },
        {
            "Short Description": "Deploy authentication service v3.0.0",
            "Long Description": "Major authentication service upgrade with OAuth 2.0 and MFA support. Extensively tested in staging for 3 weeks.",
            "Change Type": "normal",
            "Change Category": "deployment",
            "Implementation Steps": "1. Deploy v3.0.0 to canary (5% users)\n2. Monitor for errors for 30 min\n3. Increase to 50% gradually\n4. Full deployment after 2 hours\n5. Keep v2.5.0 running for quick rollback",
            "Validation Steps": "1. Login functionality works\n2. MFA enrollment works\n3. OAuth providers functional\n4. No auth service errors\n5. Error rate <0.1%",
            "Rollback Plan": "Route traffic back to v2.5.0, send logs for investigation",
            "Planned Window": "2024-02-23T23:00:00Z",
            "Impacted Services": "Authentication Service, API Gateway, Web Frontend, Mobile App",
            "Complexity": "high",
        },
        {
            "Short Description": "Disable old deprecated API v1 endpoints",
            "Long Description": "Disabling API v1 endpoints deprecated 6 months ago. All clients have migrated. Endpoints will return 410 Gone.",
            "Change Type": "normal",
            "Change Category": "deployment",
            "Implementation Steps": "1. Update API gateway routing\n2. Remove v1 route mappings\n3. Add 410 responses for v1\n4. Update documentation\n5. Send to clients",
            "Validation Steps": "1. v1 endpoints return 410\n2. v2 endpoints still work\n3. No internal services use v1\n4. Monitor for client complaints",
            "Rollback Plan": "Restore v1 routing if clients still using (unlikely)",
            "Planned Window": "2024-02-24T00:00:00Z",
            "Impacted Services": "API Gateway, External Clients",
            "Complexity": "medium",
        },
        {
            "Short Description": "ElasticSearch cluster upgrade 7.x to 8.x",
            "Long Description": "Major ElasticSearch version upgrade. Major index format changes. 3-cluster setup, rolling upgrade strategy.",
            "Change Type": "normal",
            "Change Category": "infrastructure",
            "Implementation Steps": "1. Upgrade node 1: systemctl stop elasticsearch\n2. Install ES 8.x\n3. systemctl start elasticsearch\n4. Wait for cluster recovery\n5. Repeat for node 2, 3",
            "Validation Steps": "1. Check cluster health: green\n2. Shard distribution correct\n3. Index queries still work\n4. No data loss",
            "Rollback Plan": "Downgrade nodes if critical issues found",
            "Planned Window": "2024-02-25T02:00:00Z",
            "Impacted Services": "Search, Logging, Analytics",
            "Complexity": "high",
        },
        {
            "Short Description": "Add Slack integration to incident alerts",
            "Long Description": "Integrating PagerDuty with Slack to send incident alerts to #incidents channel. Webhook-based integration.",
            "Change Type": "standard",
            "Change Category": "configuration",
            "Implementation Steps": "1. Create Slack webhook in channel settings\n2. Configure PagerDuty integration\n3. Test with sample alert\n4. Enable for all incident types",
            "Validation Steps": "1. Trigger test incident\n2. Verify Slack notification received\n3. Check message formatting\n4. Verify actionable info present",
            "Rollback Plan": "Disable Slack notification in PagerDuty",
            "Planned Window": "2024-02-20T10:00:00Z",
            "Impacted Services": "Incident Management, Slack Workspace",
            "Complexity": "low",
        },
        {
            "Short Description": "Infrastructure as Code migration to Terraform",
            "Long Description": "Migrating from manual AWS CloudFormation to Terraform IaC. Large scope affecting all infrastructure.",
            "Change Type": "normal",
            "Change Category": "infrastructure",
            "Implementation Steps": "1. Write Terraform modules for all components\n2. Dry run: terraform plan\n3. Stage environment first\n4. Import existing AWS resources: terraform import\n5. Gradually deploy to prod",
            "Validation Steps": "1. All resources created identically\n2. No resources added/removed\n3. Security groups correct\n4. Network connectivity working",
            "Rollback Plan": "Keep CloudFormation running in parallel for 30 days",
            "Planned Window": "2024-02-26T22:00:00Z",
            "Impacted Services": "All Infrastructure, CI/CD Pipeline",
            "Complexity": "high",
        },
        {
            "Short Description": "Network switch firmware update",
            "Long Description": "Critical network switch firmware update from 12.1 to 12.5. Resolves performance issues.",
            "Change Type": "normal",
            "Change Category": "infrastructure",
            "Implementation Steps": "1. Download firmware 12.5\n2. Backup current config\n3. Reboot switch to boot new firmware\n4. Verify all ports coming up\n5. Run diagnostic tests",
            "Validation Steps": "1. All ports up and running\n2. Throughput normal\n3. Latency acceptable\n4. No packet loss",
            "Rollback Plan": "Reboot with old firmware version",
            "Planned Window": "2024-02-23T02:00:00Z",
            "Impacted Services": "All Network Traffic",
            "Complexity": "high",
        },
        {
            "Short Description": "Kubernetes cluster upgrade to 1.29",
            "Long Description": "Kubernetes master/node upgrade from 1.27 to 1.29. 2-node cluster with in-place upgrade.",
            "Change Type": "normal",
            "Change Category": "infrastructure",
            "Implementation Steps": "1. Drain node 1: kubectl drain node1\n2. Upgrade kubelet and kubeadm\n3. kubeadm upgrade node\n4. Uncordon node\n5. Repeat for node 2",
            "Validation Steps": "1. All pods rescheduled successfully\n2. Services still responsive\n3. Storage volumes mounted\n4. Check kubectl version",
            "Rollback Plan": "Downgrade nodes if cluster unstable",
            "Planned Window": "2024-02-24T01:00:00Z",
            "Impacted Services": "All Containerized Services",
            "Complexity": "high",
        },
        {
            "Short Description": "Update DNS failover for disaster recovery",
            "Long Description": "Updating Route53 health checks and failover rules to account for new secondary data center.",
            "Change Type": "standard",
            "Change Category": "configuration",
            "Implementation Steps": "1. Create health check for new data center API\n2. Update Route53 record with failover policy\n3. Set health check threshold\n4. Test failover behavior\n5. Monitor DNS resolution",
            "Validation Steps": "1. Resolve primary DC IP when healthy\n2. Resolve secondary DC IP when primary unhealthy\n3. Failover time <30 seconds\n4. Both IPs accessible",
            "Rollback Plan": "Restore original Route53 config",
            "Planned Window": "2024-02-21T20:00:00Z",
            "Impacted Services": "DNS, Load Balancing, All Services",
            "Complexity": "medium",
        },
    ]
    
    # Convert to DataFrame
    df = pd.DataFrame(samples)
    
    # Create sample_data directory if not exists
    sample_dir = Path(__file__).parent / "sample_data"
    sample_dir.mkdir(exist_ok=True)
    
    # Write to Excel
    output_file = sample_dir / "sample_changes.xlsx"
    df.to_excel(output_file, index=False, sheet_name="Changes")
    
    print(f"Generated sample data with {len(samples)} change requests")
    print(f"File: {output_file}")
    
    return output_file

if __name__ == "__main__":
    generate_sample_data()
